apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: notification-service
data:
  rabbitmq.conf: |
    vm_memory_high_watermark.absolute = 256MB
    disk_free_limit.absolute = 1GB
